### ISSUE TITLE
Doesn't "click" Ok when buying baits

### ISSUE THREAD

**Issue by onyx123ff** [SoliaRdi/sell-angler-tokens#11]
If you manually click Ok it continues and sell the baits.
But when it tries to buy again doesn't click Ok to buy them.

**Comment by SoliaRdi** [comment]
You have incorrect def\opcode

**Comment by onyx123ff** [comment]
Hmm will check it then.

**Comment by onyx123ff** [comment]
Opcodes are right and im using the def that you uploaded so. Idk.
Im tryng to use on NA btw.
Opcodes: 
C_MEDAL_STORE_BUY_ADD_BASKET = 41593
C_MEDAL_STORE_COMMIT = 28747
C_STORE_COMMIT = 55033
C_STORE_SELL_ADD_BASKET = 54153
S_MEDAL_STORE_BASKET = 41478
S_STORE_BASKET = 24779

**Comment by SoliaRdi** [comment]
defs correct too?

**Comment by onyx123ff** [comment]
Yes. The ones you upload here and on auto-fishing.

**Comment by SoliaRdi** [comment]
C_STORE_COMMIT = 29419

**Comment by SoliaRdi** [comment]
![image](https://user-images.githubusercontent.com/34610562/56167738-a3afd280-5fe1-11e9-883f-758f7b7c4af2.png)

**Comment by onyx123ff** [comment]
Changed didnt work. xD

**Comment by SoliaRdi** [comment]
Did you restart proxy?

**Comment by onyx123ff** [comment]
Yes

**Comment by SoliaRdi** [comment]
Then dk, for me all working. Try debug crafted client packets, if some field has zero in this 6 opcodes

**Comment by SoliaRdi** [comment]
btw
![image](https://user-images.githubusercontent.com/34610562/56168430-db1f7e80-5fe3-11e9-8430-3facd784e9a8.png)

**Comment by SoliaRdi** [comment]
idk why you playing with wrong opcodes without any checks

**Comment by onyx123ff** [comment]
Lol wth must get confused while putting those. Shit. Thanks... working

**Comment by onyx123ff** [comment]
Shit look tho. Its wrong when i looked for the opcode using PacketsLogger.
![image](https://user-images.githubusercontent.com/33734014/56168778-2a48bd80-5faa-11e9-8d43-f12c45e01711.png)
![image](https://user-images.githubusercontent.com/33734014/56168803-40ef1480-5faa-11e9-88c5-bd3fb38b042d.png)

**Comment by SoliaRdi** [comment]
Look at number i post 8 mins ago and compare them

**Comment by SoliaRdi** [comment]
Dont forget to compare names too
