### ISSUE TITLE
cannot read property 'id' of null at sellRecipes

### ISSUE THREAD

**Issue by tsunpot** [SoliaRdi/sell-angler-tokens#14]
https://gyazo.com/ea98184f1c2e2d110795805f076bcb0f

I got this window when trying to run selltokens in newest patch in NA, I have all the new opcodes from snooping for them, but idk what needs to be changed within the module

**Comment by RobinNorling** [comment]
Seems you may have the wrong opcode or definition, try this:

https://github.com/RobinNorling/sell-angler-tokens
