### ISSUE TITLE
Not work on RU

### ISSUE THREAD

**Issue by QQakeQ** [SoliaRdi/sell-angler-tokens#3]
![screenshot](https://user-images.githubusercontent.com/47779099/53011190-e1b0d000-3450-11e9-817b-ed09d797a3d9.png)

**Comment by Moriang27** [comment]
Включи мозг, там же написано где ошибка и как исправить, это делов на 3 секунды!

**Comment by SoliaRdi** [comment]
Oops, missed the notice
